global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: go_xx_service
    metrics_path: /prometheus
    static_configs:
      - targets:
          - 192.168.31.71:8080