version: '3'

services:
  ttt:
    build:
      context: .
      dockerfile: compose/Dockerfile
    image: ttt
    container_name: ttt
    working_dir: /app
    volumes:
      - "./build:/app/build"
    command: /app/build/main